/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c00aafa8-09cf-4cf2-b89e-2d81c9cd816a",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_JUGSG3S7N",
    "aws_user_pools_web_client_id": "711d5a6qi2duhqfcf3nldpm361",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pva2vvpvdzazjm2i4ao4rcuidm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jlh2wtpf2reqdhpgge27undf2e",
    "aws_user_files_s3_bucket": "kanban62737-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
