/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c00aafa8-09cf-4cf2-b89e-2d81c9cd816a",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_JUGSG3S7N",
    "aws_user_pools_web_client_id": "711d5a6qi2duhqfcf3nldpm361",
    "oauth": {}
};


export default awsmobile;
